// регламенты

export const REGLAMENTS_GENERATE = 'REGLAMENTS_GENERATE'
export const REGLAMENTS_PUSH = 'REGLAMENTS_SET'
export const REGLAMENTS_CLEAR = 'REGLAMENTS_CLEAR'
export const REGLAMENTS_STATUS_SET = 'REGLAMENTS_STATUS_SET'

// слайды

export const SLIDES_CHANGE_VISIBLE = 'SLIDES_CHANGE_VISIBLE'
